### ISSUE TITLE
Missing index.js in published packages after 1.0.8

### ISSUE THREAD

**Issue by ryanramage** [wilmoore/selectn.js#28]
For some reason, using published versions after 1.0.8 the index.js file is missing, so require('selectn') fails.

**Comment by felixcrive** [comment]
With the latest version `import` syntax doesn't work either. Using 1.0.9.

**Comment by wilmoore** [comment]
Thanks for this report @ryanramage and @felixcrive. I appreciate it. There is something going on with `npm` where using the `files` key in `package.json` stopped working as it worked before. I am not sure if `files` using files along with an entry of `selectn.js` in `.gitignore` has edge-cases, but I was able to mitigate whatever issue is going on by dropping the `files` list and using an `.npmignore` file.

It's definitely an `npm` issue because I downloaded a few .zip releases and the `index.js` existed in each of the .zips I downloaded:

https://github.com/wilmoore/selectn.js/releases

On the other hand, I was able to verify that doing an `npm install` for those same releases came with no `index.js`.

I've documented the fix here: https://github.com/wilmoore/selectn.js/blob/master/changelog.md#1017---2016-05-02

You should be good to go by updating to the latest patch release.

Thanks again!

**Comment by sindresorhus** [comment]
This is a known bug in npm, see: https://github.com/npm/npm/issues/5082

**Comment by wilmoore** [comment]
> This is a known bug in npm, see: npm/npm#5082

Nice, thanks for that @sindresorhus
